# Generated by Django 4.0.3 on 2022-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_send', models.TextField(max_length=600)),
                ('answer', models.FileField(upload_to='media/')),
                ('data', models.DateField()),
            ],
        ),
    ]
