# Generated by Django 4.0.4 on 2022-05-02 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_block', models.IntegerField(default=0)),
                ('num_lessons', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('readable_name', models.CharField(max_length=500)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('video', models.CharField(max_length=1000)),
                ('theme', models.CharField(default=0, max_length=1000)),
                ('what_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.block')),
            ],
        ),
        migrations.CreateModel(
            name='SecondPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default=0, max_length=500)),
                ('path_to_task', models.CharField(max_length=500)),
                ('path_to_key', models.CharField(max_length=500)),
                ('date_open', models.DateField()),
                ('date_up_key', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('num_question', models.IntegerField(default=0)),
                ('theme', models.CharField(max_length=500)),
                ('what_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.block')),
                ('what_lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_area.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_points', models.IntegerField()),
                ('data_created', models.DateTimeField()),
                ('status_check', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('max_point', models.IntegerField(default=1)),
                ('number', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=False)),
                ('right_answer', models.CharField(default='', max_length=200)),
                ('what_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.test')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSecondPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='second_part/')),
                ('date', models.DateField()),
                ('status_check', models.IntegerField(default=0)),
                ('second_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.secondpart')),
                ('who_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_task', models.IntegerField(default=0)),
                ('answer', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('result_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.result')),
                ('who_send', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EveryQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=-1)),
                ('num_question', models.IntegerField(default=0)),
                ('user_answer', models.CharField(max_length=500)),
                ('result_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.result')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('photo_or_not', models.BooleanField(default=False)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_area.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_area.question')),
                ('result', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='student_area.result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
