# Generated by Django 4.0.3 on 2022-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='homework',
            name='answer',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
