# Generated by Django 4.0.3 on 2022-04-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0002_rename_data_homework_date_alter_homework_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='who_send',
            field=models.CharField(max_length=600),
        ),
    ]
