# Generated by Django 4.0.3 on 2022-04-16 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student_area.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_area', '0003_alter_homework_who_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='file_name',
            field=models.CharField(default='Task_file.docx', max_length=200),
        ),
        migrations.AddField(
            model_name='homework',
            name='num_task',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='homework',
            name='answer',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='homework',
            name='who_send',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
