# Generated by Django 4.0.3 on 2022-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0004_homework_file_name_homework_num_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='file_name',
        ),
        migrations.AlterField(
            model_name='homework',
            name='answer',
            field=models.FileField(upload_to='file/'),
        ),
    ]
