# Generated by Django 4.0.3 on 2022-04-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0007_question_alter_homework_who_send_choice_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='lock_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
