# Generated by Django 4.0.3 on 2022-04-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0008_choice_lock_other_question_visible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created',
            new_name='data_created',
        ),
        migrations.AddField(
            model_name='answer',
            name='right_or_not',
            field=models.BooleanField(default=None),
        ),
    ]
