# Generated by Django 4.0.3 on 2022-04-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0010_remove_answer_right_or_not_choice_right_or_not'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_lessons', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=200)),
                ('what_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.block')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='num_test',
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('theme', models.CharField(max_length=500)),
                ('what_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.block')),
                ('what_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='what_test',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_area.test'),
        ),
    ]
