# Generated by Django 4.0.3 on 2022-04-26 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0011_block_lesson_remove_question_num_test_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='what_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_area.test'),
        ),
    ]
