# Generated by Django 4.0.3 on 2022-04-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0013_lesson_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
