# Generated by Django 4.0.3 on 2022-04-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0015_remove_lesson_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='num_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
