# Generated by Django 4.0.3 on 2022-04-27 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0016_test_num_question_alter_test_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='what_lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_area.lesson'),
        ),
    ]
