# Generated by Django 4.0.3 on 2022-04-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0018_choice_number_alter_question_what_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
