# Generated by Django 4.0.3 on 2022-04-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0019_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='num_task',
        ),
    ]
