# Generated by Django 4.0.3 on 2022-04-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0020_remove_question_num_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='lock_other',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='right_or_not',
        ),
        migrations.AddField(
            model_name='question',
            name='right_answer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.CharField(max_length=200),
        ),
    ]
