# Generated by Django 4.0.3 on 2022-04-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0021_remove_choice_lock_other_remove_choice_right_or_not_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='data_created',
        ),
    ]
