# Generated by Django 4.0.3 on 2022-04-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0032_alter_result_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveryQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=-1)),
                ('num_question', models.IntegerField(default=0)),
                ('result_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.result')),
            ],
        ),
    ]
