# Generated by Django 4.0.3 on 2022-04-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0034_alter_result_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.CharField(max_length=1000),
        ),
    ]
