# Generated by Django 4.0.3 on 2022-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0037_block_num_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='readable_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
