# Generated by Django 4.0.3 on 2022-05-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0043_alter_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='number',
        ),
        migrations.AddField(
            model_name='choice',
            name='photo_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
