# Generated by Django 4.0.3 on 2022-05-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0044_remove_choice_number_choice_photo_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='theme',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
