# Generated by Django 4.0.3 on 2022-05-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0045_lesson_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='everyquestionchoice',
            name='user_answer',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
