# Generated by Django 4.0.3 on 2022-05-02 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_area', '0046_everyquestionchoice_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_task', models.CharField(max_length=500)),
                ('path_to_key', models.CharField(max_length=500)),
                ('date_open', models.DateField()),
                ('date_up_key', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkSecondPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.FileField(upload_to='second_part/')),
                ('date', models.DateField()),
                ('second_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_area.secondpart')),
                ('who_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
