# Generated by Django 4.0.3 on 2022-05-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_area', '0048_secondpart_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksecondpart',
            name='status_check',
            field=models.IntegerField(default=0),
        ),
    ]
