# Generated by Django 4.0.3 on 2022-04-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student_tutor_delete_userprofile_student_tutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='upgrade',
        ),
    ]
