# Generated by Django 4.0.3 on 2022-04-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_student_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upgrade',
            field=models.BooleanField(default=False),
        ),
    ]
