# Generated by Django 4.0.3 on 2022-05-02 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_area', '0002_rename_num_result_checkresult_id_second_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkresult',
            old_name='id_second_part',
            new_name='id_h_second_part',
        ),
    ]
